# Generated by Django 5.0.4 on 2024-04-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_cartproduct_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('product', 'cart')},
        ),
    ]
