# Generated by Django 5.0.4 on 2024-04-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_cartproduct_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='user',
            new_name='order',
        ),
    ]
