# Generated by Django 5.0.4 on 2024-04-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_rename_user_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(),
        ),
    ]
