# Generated by Django 5.0.4 on 2024-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.UUIDField(auto_created=True, null=True),
        ),
    ]
