# Generated by Django 5.0.4 on 2024-04-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0006_order_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
