# Generated by Django 5.0.4 on 2024-04-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
